### ISSUE TITLE
希望更改字体安装后的显示名称

### ISSUE THREAD

**Issue by Cairl** [Warren2060/Chill-G-Sans#1]
Chill-K-Sans 和 Chill-G-Sans 是我最常用的两个字体，但在电脑里这两个字体显示的名称不属于同一个格式，其中寒蝉高黑体的名称为“ChillGSans”，希望能和“Chill-K-Sans”保持同种格式命名。

感谢提供开源字体！

**Comment by Warren2060** [comment]
已修复。
